spring:
  datasource:
    url: jdbc:mysql://localhost:3306/codehouse
    username: root
    password: codehouse
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update


